# Copyright (c) ZeroC, Inc.

import Ice

# Slice module VisitorCenter in Greeter.ice maps to Python module VisitorCenter.
import VisitorCenter


class Chatbot(VisitorCenter.Greeter):
    """
    Chatbot is an Ice servant that implements Slice interface Greeter.
    """

    def __init__(self, greeterName: str):
        """
        Initializes the Chatbot servant.

        Parameters
        ----------
        greeterName : str
            The name of the greeter.
        """
        self._greeterName = greeterName

    # Implements the method greet from the Greeter class generated by the Slice compiler.
    def greet(self, name: str, current: Ice.Current) -> str:
        print(f"Dispatching greet request {{ name = '{name}' }}")
        return f"Hello, {name}! My name is {self._greeterName}. How are you doing today?"
