#!/usr/bin/env python
# Copyright (c) ZeroC, Inc.

import Ice
import chatbot
import sys


def main():
    # Create an Ice communicator. We'll use this communicator to create an object adapter.
    # IceGrid starts this server with --Ice.Config=<config file generated by IceGrid>, so it's essential to initialize
    # this communicator with sys.argv args.
    with Ice.initialize(sys.argv) as communicator:
        # Create an object adapter. It's configured by the GreeterAdapter.* properties in the IceGrid-generated config
        # file.
        adapter = communicator.createObjectAdapter("GreeterAdapter")

        # Retrieve the greeter name and greeter identity from the IceGrid-generated config file.
        properties = communicator.getProperties()
        greeterName = properties.getProperty("Ice.ProgramName")
        greeterIdentity = Ice.stringToIdentity(
            properties.getProperty("Greeter.Identity")
        )

        # Register the Chatbot servant with the adapter.
        adapter.add(chatbot.Chatbot(greeterName), greeterIdentity)

        # Start dispatching requests.
        adapter.activate()
        print(f"{greeterName} is listening...")

        try:
            # Wait until communicator.shutdown() is called, which never occurs in this demo.
            communicator.waitForShutdown()
        except KeyboardInterrupt:
            print("Caught Ctrl+C, exiting...")


if __name__ == "__main__":
    main()
