// Copyright (c) ZeroC, Inc.

package com.example.ice.endpointselection.server;

import com.example.visitorcenter.Greeter;
import com.zeroc.Ice.Current;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements Greeter {
    private final String _serverName;

    Chatbot(String serverName) {
        this._serverName = serverName;
    }

    // Implements the abstract method 'greet' from the Greeter interface generated by the Slice compiler.
    @Override
    public String greet(String name, Current current) {
        System.out.println("Dispatching greet request { name = '" + name + "' }");
        return "Hello, " + name + "! You reached " + _serverName + ".";
    }
}
