// Copyright (c) ZeroC, Inc.

import Ice

/// Chatbot is an Ice servant that implements Slice interface Greeter.
struct Chatbot: Greeter {
    // Implements the method greet from the Greeter protocol generated by the Slice compiler.
    // This version uses Asynchronous Method Dispatch (AMD). It uses the same Slice definitions as the synchronous
    // version (see Server).
    func greet(name: String, current _: Ice.Current) async throws -> String {
        try await Task.sleep(for: .seconds(1))  // Simulate a delay

        print("Dispatching greet request { name = '\(name)' }")
        return "Hello, \(name)!"
    }
}
