// Copyright (c) ZeroC, Inc.

import Ice

/// Chatbot is an Ice servant that implements Slice interface Greeter.
class Chatbot: Greeter {

    // Implements the protocol method greet from the Greeter protocol generated by the Slice compiler.
    func greet(name: String, current _: Ice.Current) throws -> String {
        print("Dispatching greet request { name = '\(name)' }")
        return "Hello, \(name)!"
    }
}
