// Copyright (c) ZeroC, Inc.

package com.example.ice.cancellation.client;

import com.example.visitorcenter.GreeterPrx;
import com.zeroc.Ice.Communicator;
import com.zeroc.Ice.InvocationTimeoutException;
import com.zeroc.Ice.OperationInterruptedException;
import com.zeroc.Ice.UnknownException;
import com.zeroc.Ice.Util;

import java.util.concurrent.CancellationException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;

class Client {
    public static void main(String[] args) {
        // Create an Ice communicator. We'll use this communicator to create proxies and manage outgoing connections.
        try (Communicator communicator = Util.initialize(args)) {
            // GreeterPrx is a class generated by the Slice compiler. We create a proxy from a communicator and a
            // "stringified proxy" with the address of the target object.
            // If you run the server on a different computer, replace localhost in the string below with the server's
            // hostname or IP address.
            GreeterPrx greeter = GreeterPrx.createProxy(communicator, "greeter:tcp -h localhost -p 4061");

            // Create a proxy to the slow greeter. It uses the same connection as the regular greeter.
            GreeterPrx slowGreeter = GreeterPrx.createProxy(communicator, "slowGreeter:tcp -h localhost -p 4061");

            // Send a request to the regular greeter and get the response.
            String greeting = greeter.greet(System.getProperty("user.name"));
            System.out.println(greeting);

            // Send a request to the slow greeter asynchronously, and cancel this request after 4 seconds.
            CompletableFuture<String> future = slowGreeter.greetAsync("alice");
            try {
                Thread.sleep(4000);
            } catch (InterruptedException exception) {
                assert false;
            }
            future.cancel(false); // the parameter is ignored, as the implementation does not use interrupts.
            try {
                greeting = future.get();
                System.out.println("Received unexpected greeting: " + greeting);
            } catch (CancellationException exception) {
                System.out.println("Caught CancellationException, as expected.");
            } catch (InterruptedException | ExecutionException exception) {
                System.out.println("Caught unexpected exception: " + exception.getMessage());
            }

            // Send a request to the slow greeter, and interrupt this thread after 4 seconds to cancel the request.
            var mainThread = Thread.currentThread();
            CompletableFuture.delayedExecutor(4, TimeUnit.SECONDS).execute(() -> {
                // The connection is aborted if the interrupt is delivered to the thread while it performs I/O (not
                // shown in this demo).
                mainThread.interrupt();
            });

            try {
                greeting = slowGreeter.greet("bob");
                System.out.println("Received unexpected greeting: " + greeting);
            } catch (OperationInterruptedException exception) {
                System.out.println("Caught OperationInterruptedException, as expected.");

                // Ice resets the interrupted status of the thread when it throws an OperationInterruptedException.
                assert !mainThread.isInterrupted();
            }

            // Create another slow greeter proxy with an invocation timeout of 4 seconds (the default invocation timeout
            // is infinite).
            GreeterPrx slowGreeter4s = slowGreeter.ice_invocationTimeout(4);

            // Send a request to the slow greeter with the 4-second invocation timeout.
            try {
                greeting = slowGreeter4s.greet("carol");
                System.out.println("Received unexpected greeting: " + greeting);
            } catch (InvocationTimeoutException exception) {
                System.out.println("Caught InvocationTimeoutException, as expected: " + exception.getMessage());
            }

            // Verify the regular greeter still works.
            greeting = greeter.greet("dave");
            System.out.println(greeting);

            // Send a request to the slow greeter, and wait forever for the response.
            System.out.println("Please press Ctrl+C in the server's terminal to cancel the slow greeter dispatch.");
            try {
                greeting = slowGreeter.greet("eve");
                System.out.println(greeting);
            } catch (UnknownException exception) {
                System.out.println("Caught UnknownException, as expected: " + exception.getMessage());
            }
        }
    }
}
