// Copyright (c) ZeroC, Inc.

#ifndef CHATBOT_H
#define CHATBOT_H

#include "Greeter.h"

namespace GreeterServer
{
    /// A Chatbot is an Ice servant that implements Slice interface Greeter.
    class Chatbot : public VisitorCenter::Greeter
    {
    public:
        // Waits for all tasks to complete
        ~Chatbot() override;

        // Implements the pure virtual function in the base class (VisitorCenter::Greeter) generated by the Slice
        // compiler.
        void greetAsync(
            std::string name,
            std::function<void(std::string_view returnValue)> response,
            std::function<void(std::exception_ptr)> exception,
            const Ice::Current& current) override;

    private:
        std::vector<std::future<void>> _tasks;
    };
}

#endif
