// Copyright (c) ZeroC, Inc.

package com.example.ice.greeter.serveramd;

import com.example.visitorcenter.AsyncGreeter;
import com.zeroc.Ice.Current;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.TimeUnit;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements AsyncGreeter {
    // Implements the abstract method 'greetAsync' from the AsyncGreeter interface generated by the Slice compiler.
    @Override
    public CompletionStage<String> greetAsync(String name, Current current) {
        System.out.println("Dispatching greet request { name = '" + name + "' }");

        return CompletableFuture.supplyAsync(
            () -> "Hello, " + name + "!",
            CompletableFuture.delayedExecutor(1, TimeUnit.SECONDS)
        );
    }
}
