// Copyright (c) ZeroC, Inc.

#ifndef CHATBOT_H
#define CHATBOT_H

#include "Greeter.h"

namespace Server
{
    /// Chatbot is an Ice servant that implements Slice interface Greeter.
    class Chatbot : public VisitorCenter::Greeter
    {
    public:
        /// Constructors a Chatbot servant.
        /// @param greeterName The name of the greeter.
        explicit Chatbot(std::string greeterName);

        // Implements the pure virtual function in the base class (VisitorCenter::Greeter) generated by the Slice
        // compiler.
        std::string greet(std::string name, const Ice::Current&) override;

    private:
        std::string _greeterName;
    };
}

#endif
