// Copyright (c) ZeroC, Inc.

import Ice

/// Chatbot is an Ice servant that implements Slice interface Greeter.
struct ChatBot: Greeter {
    // Implements the method greet from the Greeter protocol generated by the Slice compiler.
    func greet(name: String, current: Ice.Current) -> String {
        // We retrieve the value for the language entry in the context.
        let language = current.ctx["language"] ?? ""

        print("Dispatching greet request { name = '\(name)', language = '\(language)' }")

        // Return a greeting in the requested language.
        return switch language {
        case "de": "Hallo \(name), wie geht's?"
        case "es": "¡Hola \(name)!"
        case "fr": "Bonjour \(name), comment vas-tu ?"
        default: "Hello, \(name)!"
        }
    }
}
