// Copyright (c) ZeroC, Inc.

using VisitorCenter;

namespace CustomErrorServer;

/// <summary>Chatbot is an Ice servant that implements Slice interface Greeter.</summary>
internal class Chatbot : GreeterDisp_
{
    private const int MaxLength = 7;

    /// <inheritdoc/>
    // Implements the abstract method Greet from the GreeterDisp_ class generated by the Slice compiler.
    // This variant is the synchronous implementation.
    public override string Greet(string name, Ice.Current current)
    {
        Console.WriteLine($"Dispatching greet request {{ name = '{name}' }}");

        if (name.Length > MaxLength)
        {
            throw new GreeterException("Name is longer than maximum!", GreeterError.NameTooLong);
        }
        switch (name)
        {
            case "":
                throw new GreeterException("Name is empty!", GreeterError.EmptyName);
            case "jimmy":
                Thread.Sleep(5000);
                throw new GreeterException("Delayed response!", GreeterError.Away);
            default:
                return $"Hello, {name}!";
        }
    }
}
