// Copyright (c) ZeroC, Inc.

using VisitorCenter;

namespace Server;

/// <summary>Chatbot is an Ice servant that implements Slice interface Greeter.</summary>
internal class Chatbot : GreeterDisp_
{
    private const int MaxLength = 7;

    /// <inheritdoc/>
    // Implements the abstract method Greet from the GreeterDisp_ class generated by the Slice compiler.
    public override string Greet(string name, Ice.Current current)
    {
        Console.WriteLine($"Dispatching greet request {{ name = '{name}' }}");

        // Depending on the name, we return a greeting or throw an exception.
        return name switch
        {
            "" =>
                // ObjectNotExistException is a dispatch exception with a reply status of 'ObjectNotExist'.
                throw new Ice.ObjectNotExistException(),
            "alice" =>
                // / Simulate an authentication error by throwing a dispatch exception with the Unauthorized error code.
                // Note: This is a demo; no real authentication logic is implemented.
                throw new Ice.DispatchException(
                    Ice.ReplyStatus.Unauthorized,
                    "Invalid credentials. The administrator has been notified."),
            "bob" =>
                throw new GreeterException($"Away until {DateTime.Now + TimeSpan.FromMinutes(5)}.", GreeterError.Away),
            "carol" =>
                throw new GreeterException("I am already greeting someone else.", GreeterError.GreetingOtherVisitor),
            _ when name.Length > MaxLength =>
                throw new GreeterException("Name is longer than maximum!", GreeterError.NameTooLong),
            _ => $"Hello, {name}!"
        };
    }
}
