# Copyright (c) ZeroC, Inc.

import asyncio

import Ice

# Slice module VisitorCenter in Greeter.ice maps to Python module VisitorCenter.
import VisitorCenter


class Chatbot(VisitorCenter.Greeter):
    """
    Chatbot is an Ice servant that implements Slice interface Greeter.
    """

    def __init__(self, delay: float | None = None):
        """
        Initializes a Chatbot servant with an optional delay.

        Parameters
        ----------
        delay : float | None
            The delay before returning each greeting, or None for no delay.
        """
        self._delay = delay
        self._canceled = False
        self._outstandingTasks: set[asyncio.Task[None]] = set()

    # Implements the method greet from the Greeter class generated by the Slice compiler.
    async def greet(self, name: str, current: Ice.Current) -> str:
        print(f"Dispatching greet request {{ name = '{name}' }}")
        if self._delay is not None:
            # Once cancelOutstandingTasks has been called, fail new dispatches immediately instead of sleeping.
            if not self._canceled:
                task = asyncio.create_task(asyncio.sleep(self._delay))
                self._outstandingTasks.add(task)
                try:
                    # Raises a CancelledError when the task is canceled by cancelOutstandingTasks.
                    await task
                except asyncio.CancelledError:
                    dispatchTask = asyncio.current_task()
                    if dispatchTask is not None and dispatchTask.cancelling() > 0:
                        # The dispatch task itself was canceled from outside; let the cancellation propagate.
                        raise
                finally:
                    self._outstandingTasks.discard(task)
            if self._canceled:
                message = f"greet dispatch canceled {{ name = '{name}' }}"
                print(message)
                raise Ice.UnknownException(message) from None
        return f"Hello, {name}!"

    def cancelOutstandingTasks(self) -> None:
        """
        Cancels all outstanding tasks and makes further dispatches fail immediately.
        """
        self._canceled = True
        for task in self._outstandingTasks:
            task.cancel()
