# Copyright (c) ZeroC, Inc.

import asyncio

import Ice

# Slice module VisitorCenter in Greeter.ice maps to Python module VisitorCenter.
import VisitorCenter


class Chatbot(VisitorCenter.Greeter):
    """
    Chatbot is an Ice servant that implements Slice interface Greeter.
    """

    def __init__(self, delay: float):
        """
        Initializes a Chatbot servant with a delay.

        Parameters
        ----------
        delay : float
            The delay before returning each greeting.
        """
        self._delay = delay
        self._outstandingTasks: set[asyncio.Task] = set()

    # Implements the method greet from the Greeter class generated by the Slice compiler.
    async def greet(self, name: str, current: Ice.Current) -> str:
        print(f"Dispatching greet request {{ name = '{name}' }}")
        task = asyncio.ensure_future(asyncio.sleep(self._delay))
        self._outstandingTasks.add(task)
        try:
            # Raises a CancelledError when the task is canceled by cancelOutstandingTasks.
            await task
        except asyncio.CancelledError:
            print(f"greet dispatch canceled {{ name = '{name}' }}")
            raise Ice.UnknownException(f"greet dispatch canceled {{ name = '{name}' }}")
        finally:
            self._outstandingTasks.discard(task)
        return f"Hello, {name}!"

    def cancelOutstandingTasks(self):
        """
        Cancels all outstanding tasks.
        """
        for task in self._outstandingTasks:
            task.cancel()
