// Copyright (c) ZeroC, Inc.

package com.example.icegrid.icebox.service;

import com.example.visitorcenter.Greeter;
import com.zeroc.Ice.Current;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements Greeter {
    private final String _greeterName;

    Chatbot(String greeterName) {
        this._greeterName = greeterName;
    }

    // Implements the abstract method 'greet' from the Greeter interface generated by the Slice compiler.
    @Override
    public String greet(String name, Current current) {
        System.out.println("Dispatching greet request { name = '" + name + "' }");
        return "Hello, " + name + "! My name is " + _greeterName + ". How are you doing today?";
    }
}
