// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6b
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("zeroc-icejs").Ice;
    var __M = Ice.__M;
    var Glacier2 = require("zeroc-icejs").Glacier2;
    var Slice = Ice.Slice;

    var Demo = __M.module("Demo");

    Demo.ChatCallback = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 0,
        [
            "::Demo::ChatCallback",
            "::Ice::Object"
        ],
        -1, undefined, undefined, false);

    Demo.ChatCallbackPrx = Slice.defineProxy(Ice.ObjectPrx, Demo.ChatCallback.ice_staticId, undefined);

    Slice.defineOperations(Demo.ChatCallback, Demo.ChatCallbackPrx,
    {
        "message": [, , , , , , [[7]], , , , ]
    });

    Demo.ChatSession = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            Glacier2.Session
        ], 0,
        [
            "::Demo::ChatSession",
            "::Glacier2::Session",
            "::Ice::Object"
        ],
        -1, undefined, undefined, false);

    Demo.ChatSessionPrx = Slice.defineProxy(Ice.ObjectPrx, Demo.ChatSession.ice_staticId, [
        Glacier2.SessionPrx]);

    Slice.defineOperations(Demo.ChatSession, Demo.ChatSessionPrx,
    {
        "setCallback": [, , , , , , [["Demo.ChatCallbackPrx"]], , , , ],
        "say": [, , , , , , [[7]], , , , ]
    });
    exports.Demo = Demo;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
