// Copyright (c) ZeroC, Inc.

package com.example.ice.cancellation.server;

import com.example.visitorcenter.Greeter;
import com.zeroc.Ice.Current;
import com.zeroc.Ice.UnknownException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.TimeUnit;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements Greeter {
    private final CompletableFuture _cancelDispatch;
    private final long _delay;

    // Creates a new Chatbot instance with a delay in seconds.
    Chatbot(CompletableFuture cancelDispatch, long delay) {
        _cancelDispatch = cancelDispatch;
        _delay = delay;
    }

    // Creates a new Chatbot instance without a delay.
    Chatbot() {
        this(null, 0);
    }

    // Implements the abstract method 'greet' from the Greeter interface generated by the Slice compiler.
    public String greet(String name, Current current) {
        System.out.println("Dispatching greet request { name = '" + name + "' }");

        // Simulate a delay in the response.
        if (_cancelDispatch != null) {
            try {
                _cancelDispatch.get(_delay, TimeUnit.SECONDS);
                System.out.println("greet dispatch canceled { name = '" + name + "' }");
                throw new UnknownException("Greet dispatch canceled.");
            } catch (TimeoutException e) {
                // Expected, proceed.
            }
            catch (InterruptedException | ExecutionException e) {
                // Unexpected, wrap and rethrow.
                throw new RuntimeException("Unexpected exception while waiting on cancelDispatch", e);
            }
        }

        return "Hello, " + name + "!";
    }
}
