// Copyright (c) ZeroC, Inc.

package com.example.ice.cancellation.server;

import com.example.visitorcenter.Greeter;
import com.zeroc.Ice.Current;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements Greeter
{
    private long _delay;

    // Creates a new Chatbot instance.
    public Chatbot(long delay) {
        _delay = delay;
    }

    // Implements the abstract method 'greetAsync' from the Greeter interface generated by the Slice compiler.
    // This variant is the asynchronous implementation.
    public String greet(String name, Current current) {
        System.out.println("Dispatching greet request { name = '" + name + "' }");

        try {
            Thread.sleep(_delay);
        }
        catch (InterruptedException exception)
        {
            System.out.println("server thread interrupted?");
        }
        return "Hello, " + name + "!";
    }
}
