// Copyright (c) ZeroC, Inc.

/// Makes AtmosphericConditions conform to the `CustomStringConvertible` protocol.
/// AtmosphericConditions is a class generated by the Slice compiler from a Slice class with the same name.
extension AtmosphericConditions: CustomStringConvertible {
    public var description: String {
        let pressureMb =
            switch pressure {
            case .none:
                "unknown"
            case .some(let p):
                "\(p) mb"
            }
        return "{ Temperature = \(temperature)°C, Humidity = \(humidity)%, Pressure = \(pressureMb) }"
    }
}
