// Copyright (c) ZeroC, Inc.

using VisitorCenter;

namespace Server;

/// <summary>Chatbot is an Ice servant that implements Slice interface Greeter.</summary>
internal class Chatbot : GreeterDisp_
{
    private readonly string _greeterName;

    /// <inheritdoc/>
    // Implements the abstract method Greet from the GreeterDisp_ class generated by the Slice compiler.
    public override string Greet(string name, Ice.Current current)
    {
        Console.WriteLine($"Dispatching greet request {{ name = '{name}' }}");
        return $"Hello, {name}! I am {_greeterName}. How can I help you today?";
    }

    /// <summary>Creates a new Chatbot instance.</summary>
    /// <param name="greeterName">The name of the new greeter.</param>
    internal Chatbot(string greeterName) => _greeterName = greeterName;
}
