// Copyright (c) ZeroC, Inc.

package com.zeroc.greeter;

import com.zeroc.greeter.VisitorCenter.Greeter;
import com.zeroc.Ice.Current;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements Greeter
{
    // Implements the abstract method Greet from the Greeter interface generated by the Slice compiler.
    // This variant is the synchronous implementation.
    public java.util.concurrent.CompletionStage<String>  greetAsync(String name, Current current)
    {
        System.out.println("Dispatching greet request { name = '" + name + "' }");

        return CompletableFuture.supplyAsync(
            () -> "Hello, " + name + "!",
            CompletableFuture.delayedExecutor(1, TimeUnit.SECONDS)
        );
    }
}
