// Copyright (c) ZeroC, Inc.

package com.example.icegrid.greeter.server;

import com.example.visitorcenter.Greeter;
import com.zeroc.Ice.Current;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements Greeter
{
    private final String _greeterName;

    // Implements the abstract method 'greet' from the Greeter interface generated by the Slice compiler.
    public String greet(String name, Current current) {
        System.out.println("Dispatching greet request { name = '" + name + "' }");
        return "Hello, " + name + "! My name is " + _greeterName + ". How are you doing today?";
    }

    /**
     * Creates a Chatbot servant.
     * @param greeterName the name of the greeter
     */
    Chatbot(String greeterName) { _greeterName = greeterName; }
}
