// Copyright (c) ZeroC, Inc.

package com.example.icegrid.greeter.server;

import com.zeroc.Ice.Communicator;
import com.zeroc.Ice.Identity;
import com.zeroc.Ice.ObjectAdapter;
import com.zeroc.Ice.Properties;
import com.zeroc.Ice.Util;

class Server {
    public static void main(String[] args) {
        // Create an Ice communicator. We'll use this communicator to create an object adapter.
        // IceGrid starts this server with --Ice.Config=<config file generated by IceGrid>, so it's essential to
        // initialize this communicator with args.
        try (Communicator communicator = Util.initialize(args)) {

            // Register a shutdown hook that calls communicator.shutdown() when the user shuts down the server with
            // Ctrl+C or similar. The shutdown hook thread also waits until the main thread completes its cleanup.
            shutdownCommunicatorOnCtrlC(communicator, Thread.currentThread());

            // Create an object adapter. It's configured by the GreeterAdapter.* properties in the IceGrid-generated config file.
            ObjectAdapter adapter = communicator.createObjectAdapter("GreeterAdapter");

            // Retrieve the greeter name and greeter identity from the IceGrid-generated config file.
            Properties properties = communicator.getProperties();
            String greeterName = properties.getProperty("Ice.ProgramName");
            Identity greeterIdentity = Util.stringToIdentity(properties.getProperty("Greeter.Identity"));

            // Register the Chatbot servant with the adapter.
            adapter.add(new Chatbot(greeterName), greeterIdentity);

            // Start dispatching requests.
            adapter.activate();
            System.out.println(greeterName + " is listening...");

            // Wait until the communicator is shut down. Here, this occurs when the user presses Ctrl+C.
            communicator.waitForShutdown();
        }
    }

    private static void shutdownCommunicatorOnCtrlC(Communicator communicator, Thread mainThread) {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Caught Ctrl+C, shutting down...");
            communicator.shutdown();

            // Wait until the main thread completes.
            try {
                mainThread.join();
            } catch (InterruptedException e) {
                // No code interrupts the shutdown hook thread in this program.
                assert false;
            }
        }));
    }
}
