// Copyright (c) ZeroC, Inc.

#include "../../common/Env.h"
#include "Greeter.h"

#include <Glacier2/Glacier2.h>
#include <Ice/Ice.h>
#include <cassert>
#include <iostream>

using namespace std;

int
main(int argc, char* argv[])
{
    // Create an Ice communicator. We'll use this communicator to create proxies and manage outgoing connections.
    Ice::CommunicatorPtr communicator = Ice::initialize(argc, argv);

    // Make sure the communicator is destroyed at the end of this scope.
    Ice::CommunicatorHolder communicatorHolder{communicator};

    // Set the default locator of the new communicator. It's the address of the Locator hosted by our IceGrid registry.
    // You can also set this proxy with the Ice.Default.Locator property.
    communicator->setDefaultLocator(Ice::LocatorPrx{communicator, "IceGrid/Locator:default -h localhost -p 4061"});

    // GreeterPrx is a class generated by the Slice compiler. We create a proxy from a communicator and a "stringified
    // proxy" with the address of the target object.
    // If you run the server on a different computer, replace localhost in the string below with the server's hostname
    // or IP address.
    VisitorCenter::GreeterPrx greeter{communicator, "greeter"};

    // Send a request to the remote object and wait synchronously for the response.
    // Both the -> and . syntax can be used to make invocations with the proxy.
    string greeting = greeter->greet(Env::getUsername());
    cout << greeting << endl;

    // Send a second request to observe the effect in the Glacier2 router log.
    greeting = greeter->greet("alice");
    cout << greeting << endl;

    return 0;
}
