// Copyright (c) ZeroC, Inc.

#ifndef DEFAULT_POKE_SESSION_H
#define DEFAULT_POKE_SESSION_H

#include "UserIdResolver.h"
#include "PokeBox.h"

namespace Server
{
    /// DefaultPokeSession is an Ice servant that implements Slice interface PokeSession. We create a
    /// DefaultPokeSession for each PokeSession object.
    class DefaultPokeSession : public CatchThemAll::PokeSession
    {
    public:
        /// Constructs a DefaultPokeSession servant.
        /// @param adapter The object adapter that hosts this servant and the PokeBox objects.
        /// @param sessionControl The session control proxy.
        /// @param userIdResolver The user ID resolver.
        DefaultPokeSession(
            Ice::ObjectAdapterPtr adapter,
            Glacier2::SessionControlPrx sessionControl,
            UserIdResolverPtr userIdResolver);

        void destroy(const Ice::Current& current) final;

        // Implements the pure virtual function in the base class (CatchThemAll::PokeSession) generated by the Slice
        // compiler.
        std::optional<CatchThemAll::PokeBoxPrx> getPokeBox(const Ice::Current&) final;

    private:
        // The object adapter that hosts this servant and the PokeBox objects.
        Ice::ObjectAdapterPtr _adapter;

        // A proxy to the SessionControl object hosted by the Glacier2 router; this proxy allows us to control the
        // Glacier2 session, in particular to destroy it. In this demo, that's the only per-session state maintained by
        // DefaultPokeSession.
        Glacier2::SessionControlPrx _sessionControl;

        UserIdResolverPtr _userIdResolver;
    };
}

#endif
