# **********************************************************************
#
# Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
#
# **********************************************************************

top_srcdir	= ../..

SLICE_SRCS	= Hello.ice

include $(top_srcdir)/make/Make.rules
