// Copyright (c) ZeroC, Inc.

// Create an Ice communicator. We'll use this communicator to create an object adapter.
// IceGrid starts this server with --Ice.Config=<config file generated by IceGrid>, so it's essential to initialize
// this communicator with ref args.
using Ice.Communicator communicator = Ice.Util.initialize(ref args);

// Create an object adapter. It's configured by the GreeterAdapter.* properties in the IceGrid-generated config file.
Ice.ObjectAdapter adapter = communicator.createObjectAdapter("GreeterAdapter");

// Retrieve the greeter name and greeter identity from the IceGrid-generated config file.
Ice.Properties properties = communicator.getProperties();
string greeterName = properties.getProperty("Ice.ProgramName");
Ice.Identity greeterIdentity = Ice.Util.stringToIdentity(properties.getProperty("Greeter.Identity"));

// Register the Chatbot servant with the adapter.
adapter.add(new Server.Chatbot(greeterName), greeterIdentity);

// Start dispatching requests.
adapter.activate();
Console.WriteLine($"{greeterName} is listening...");

// Wait until the communicator is shut down. IceGrid shuts down this communicator via its Ice.Admin object.
await communicator.shutdownCompleted;
