// Copyright (c) ZeroC, Inc.

using VisitorCenter;

namespace Service;

/// <summary>Chatbot is an Ice servant that implements Slice interface Greeter.</summary>
internal class Chatbot : GreeterDisp_
{
    private readonly string _chatbotName;

    /// <inheritdoc/>
    // Implements the abstract method Greet from the GreeterDisp_ class generated by the Slice compiler.
    // This variant is the synchronous implementation.
    public override string Greet(string name, Ice.Current current)
    {
        Console.WriteLine($"Dispatching greet request {{ name = '{name}' }}");
        return $"Hello, {name}! My name is {_chatbotName}. How can I assist you today?";
    }

    /// <summary>Creates a new instance of <see cref="Chatbot"/>.</summary>
    /// <param name="chatbotName">The name of the new chatbot.</param>
    internal Chatbot(string chatbotName) => _chatbotName = chatbotName;
}
