# Copyright (c) ZeroC, Inc.

import Ice

# Slice module VisitorCenter in Greeter.ice maps to Python module VisitorCenter.
import VisitorCenter


class Chatbot(VisitorCenter.Greeter):
    """
    Chatbot is an Ice servant that implements Slice interface Greeter.
    """

    def __init__(self, greeterName: str):
        """
        Creates a new Chatbot instance.

        Parameters
        ----------
        greeterName : str
            The name of the new greeter.
        """
        self._greeterName = greeterName

    # Implements the method greet from the Greeter class generated by the Slice compiler.
    # This variant is the synchronous implementation.
    def greet(self, name: str, current: Ice.Current) -> str:
        print(f"Dispatching greet request {{ name = '{name}' }}")
        return f"Hello, {name}! I am {self._greeterName}. How can I help you today?"
