[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "common"
version = "0.1.0"
description = "Helper functions for Ice demos"
authors = [
  { name = "ZeroC, Inc.", email = "info@zeroc.com" }
]
dependencies = []
