// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Hello_h__
#define __Hello_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef ICE_CPP11_MAPPING // C++98 mapping

namespace IceProxy
{

namespace Demo
{

class Hello;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Demo::Hello>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Demo::Hello*);

}

}

namespace Demo
{

class Hello;
bool operator==(const Hello&, const Hello&);
bool operator<(const Hello&, const Hello&);
::Ice::Object* upCast(::Demo::Hello*);
typedef ::IceInternal::Handle< ::Demo::Hello> HelloPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Demo::Hello> HelloPrx;
typedef HelloPrx HelloPrxPtr;
void __patch(HelloPtr&, const ::Ice::ObjectPtr&);

}

namespace Demo
{

class Callback_Hello_sayHello_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Hello_sayHello_Base> Callback_Hello_sayHelloPtr;

class Callback_Hello_shutdown_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Hello_shutdown_Base> Callback_Hello_shutdownPtr;

}

namespace IceProxy
{

namespace Demo
{

class Hello : virtual public ::IceProxy::Ice::Object
{
public:
    void sayHello(::Ice::Int __p_delay, const ::Ice::Context& __ctx = ::Ice::noExplicitContext)
    {
        sayHello(__p_delay, &__ctx);
    }
#ifdef ICE_CPP11_COMPILER
    ::Ice::AsyncResultPtr
    begin_sayHello(::Ice::Int __p_delay, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sayHello(__p_delay, &::Ice::noExplicitContext, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_sayHello(::Ice::Int __p_delay, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sayHello(__p_delay, &::Ice::noExplicitContext, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sayHello(::Ice::Int __p_delay, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sayHello(__p_delay, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sayHello(::Ice::Int __p_delay, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sayHello(__p_delay, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_sayHello(::Ice::Int __p_delay)
    {
        return begin_sayHello(__p_delay, &::Ice::noExplicitContext, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sayHello(::Ice::Int __p_delay, const ::Ice::Context& __ctx)
    {
        return begin_sayHello(__p_delay, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sayHello(::Ice::Int __p_delay, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sayHello(__p_delay, &::Ice::noExplicitContext, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(::Ice::Int __p_delay, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sayHello(__p_delay, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(::Ice::Int __p_delay, const ::Demo::Callback_Hello_sayHelloPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sayHello(__p_delay, &::Ice::noExplicitContext, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(::Ice::Int __p_delay, const ::Ice::Context& __ctx, const ::Demo::Callback_Hello_sayHelloPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sayHello(__p_delay, &__ctx, __del, __cookie);
    }

    void end_sayHello(const ::Ice::AsyncResultPtr&);
    
private:

    void sayHello(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_sayHello(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    void shutdown(const ::Ice::Context& __ctx = ::Ice::noExplicitContext)
    {
        shutdown(&__ctx);
    }
#ifdef ICE_CPP11_COMPILER
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_shutdown(&::Ice::noExplicitContext, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_shutdown(&::Ice::noExplicitContext, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_shutdown(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_shutdown(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_shutdown()
    {
        return begin_shutdown(&::Ice::noExplicitContext, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx)
    {
        return begin_shutdown(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(&::Ice::noExplicitContext, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Demo::Callback_Hello_shutdownPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(&::Ice::noExplicitContext, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx, const ::Demo::Callback_Hello_shutdownPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(&__ctx, __del, __cookie);
    }

    void end_shutdown(const ::Ice::AsyncResultPtr&);
    
private:

    void shutdown(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Hello> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_secure(bool __secure) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_twoway() const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_oneway() const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_batchOneway() const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_datagram() const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_batchDatagram() const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_compress(bool __compress) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Hello> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Hello*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace Demo
{

class Hello : virtual public ::Ice::Object
{
public:

    typedef HelloPrx ProxyType;
    typedef HelloPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void sayHello(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void shutdown(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___shutdown(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const Hello& l, const Hello& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Hello& l, const Hello& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Demo
{

template<class T>
class CallbackNC_Hello_sayHello : public Callback_Hello_sayHello_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Hello_sayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Hello_sayHelloPtr
newCallback_Hello_sayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_sayHello<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Hello_sayHelloPtr
newCallback_Hello_sayHello(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_sayHello<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Hello_sayHelloPtr
newCallback_Hello_sayHello(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_sayHello<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Hello_sayHelloPtr
newCallback_Hello_sayHello(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_sayHello<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Hello_sayHello : public Callback_Hello_sayHello_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Hello_sayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Hello_sayHelloPtr
newCallback_Hello_sayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_sayHello<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Hello_sayHelloPtr
newCallback_Hello_sayHello(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_sayHello<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Hello_sayHelloPtr
newCallback_Hello_sayHello(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_sayHello<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Hello_sayHelloPtr
newCallback_Hello_sayHello(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_sayHello<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Hello_shutdown : public Callback_Hello_shutdown_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Hello_shutdown(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Hello_shutdownPtr
newCallback_Hello_shutdown(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_shutdown<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Hello_shutdownPtr
newCallback_Hello_shutdown(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_shutdown<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Hello_shutdownPtr
newCallback_Hello_shutdown(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_shutdown<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Hello_shutdownPtr
newCallback_Hello_shutdown(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_shutdown<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Hello_shutdown : public Callback_Hello_shutdown_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Hello_shutdown(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Hello_shutdownPtr
newCallback_Hello_shutdown(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_shutdown<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Hello_shutdownPtr
newCallback_Hello_shutdown(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_shutdown<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Hello_shutdownPtr
newCallback_Hello_shutdown(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_shutdown<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Hello_shutdownPtr
newCallback_Hello_shutdown(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_shutdown<T, CT>(instance, 0, excb, sentcb);
}

}

#else // C++11 mapping

namespace Demo
{
class HelloPrx;
typedef ::std::shared_ptr<HelloPrx> HelloPrxPtr;

}

namespace Demo
{

class Hello;
typedef ::std::shared_ptr< Hello> HelloPtr;

}

namespace Demo
{

class HelloPrx : virtual public ::Ice::ObjectPrx
{
public:

    void sayHello(int __p_delay, const ::Ice::Context& __ctx = Ice::noExplicitContext);

    ::std::function<void ()>
    sayHello_async(int,
                   ::std::function<void ()>,
                   ::std::function<void (::std::exception_ptr)> __exception = nullptr,
                   ::std::function<void (bool)> __sent = nullptr,
                   const ::Ice::Context& __ctx = Ice::noExplicitContext);

    template<template<typename> class P = ::std::promise>
    auto sayHello_async(int __p_delay, const ::Ice::Context& __ctx = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        using Promise = P<void>;
        auto __promise = ::std::make_shared<Promise>();
        if(ice_isTwoway())
        {
            sayHello_async(__p_delay,
                           [__promise]()
                           {
                               __promise->set_value();
                           },
                           [__promise](::std::exception_ptr __ex)
                           {
                               __promise->set_exception(::std::move(__ex));
                           },
                           nullptr, __ctx);
        }
        else if(ice_isOneway() || ice_isDatagram())
        {
            sayHello_async(__p_delay,
                           nullptr,
                           [__promise](::std::exception_ptr __ex)
                           {
                               __promise->set_exception(::std::move(__ex));
                           },
                           [__promise](bool)
                           {
                               __promise->set_value();
                           },
                           __ctx);
        }
        else
        {
            sayHello_async(__p_delay,nullptr, nullptr, nullptr, __ctx);
        }
        return __promise->get_future();
    }

    void shutdown(const ::Ice::Context& __ctx = Ice::noExplicitContext);

    ::std::function<void ()>
    shutdown_async(::std::function<void ()>,
                   ::std::function<void (::std::exception_ptr)> __exception = nullptr,
                   ::std::function<void (bool)> __sent = nullptr,
                   const ::Ice::Context& __ctx = Ice::noExplicitContext);

    template<template<typename> class P = ::std::promise>
    auto shutdown_async(const ::Ice::Context& __ctx = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        using Promise = P<void>;
        auto __promise = ::std::make_shared<Promise>();
        if(ice_isTwoway())
        {
            shutdown_async([__promise]()
                           {
                               __promise->set_value();
                           },
                           [__promise](::std::exception_ptr __ex)
                           {
                               __promise->set_exception(::std::move(__ex));
                           },
                           nullptr, __ctx);
        }
        else if(ice_isOneway() || ice_isDatagram())
        {
            shutdown_async(
                           nullptr,
                           [__promise](::std::exception_ptr __ex)
                           {
                               __promise->set_exception(::std::move(__ex));
                           },
                           [__promise](bool)
                           {
                               __promise->set_value();
                           },
                           __ctx);
        }
        else
        {
            shutdown_async(nullptr, nullptr, nullptr, __ctx);
        }
        return __promise->get_future();
    }
    ::std::shared_ptr<HelloPrx> ice_context(const ::Ice::Context& __context) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(Ice::ObjectPrx::ice_context(__context));
    }
    ::std::shared_ptr<HelloPrx> ice_adapterId(const ::std::string& __id) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_adapterId(__id));
    }
    ::std::shared_ptr<HelloPrx> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_endpoints(__endpoints));
    }
    ::std::shared_ptr<HelloPrx> ice_locatorCacheTimeout(int __timeout) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_locatorCacheTimeout(__timeout));
    }
    ::std::shared_ptr<HelloPrx> ice_connectionCached(bool __cached) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_connectionCached(__cached));
    }
    ::std::shared_ptr<HelloPrx> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_endpointSelection(__est));
    }
    ::std::shared_ptr<HelloPrx> ice_secure(bool __secure) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_secure(__secure));
    }
    ::std::shared_ptr<HelloPrx> ice_preferSecure(bool __preferSecure) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_preferSecure(__preferSecure));
    }
    ::std::shared_ptr<HelloPrx> ice_router(const ::Ice::RouterPrxPtr& __router) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_router(__router));
    }
    ::std::shared_ptr<HelloPrx> ice_locator(const ::Ice::LocatorPrxPtr& __locator) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_locator(__locator));
    }
    ::std::shared_ptr<HelloPrx> ice_collocationOptimized(bool __co) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_collocationOptimized(__co));
    }
    ::std::shared_ptr<HelloPrx> ice_invocationTimeout(int __timeout) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_invocationTimeout(__timeout));
    }
    ::std::shared_ptr<HelloPrx> ice_twoway() const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_twoway());
    }
    ::std::shared_ptr<HelloPrx> ice_oneway() const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_oneway());
    }
    ::std::shared_ptr<HelloPrx> ice_batchOneway() const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_batchOneway());
    }
    ::std::shared_ptr<HelloPrx> ice_datagram() const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_datagram());
    }
    ::std::shared_ptr<HelloPrx> ice_batchDatagram() const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_batchDatagram());
    }
    ::std::shared_ptr<HelloPrx> ice_compress(bool __compress) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_compress(__compress));
    }
    ::std::shared_ptr<HelloPrx> ice_timeout(int __timeout) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_timeout(__timeout));
    }
    ::std::shared_ptr<HelloPrx> ice_connectionId(const ::std::string& __id) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_connectionId(__id));
    }
    ::std::shared_ptr<HelloPrx> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return ::std::dynamic_pointer_cast<HelloPrx>(::Ice::ObjectPrx::ice_encodingVersion(__v));
    }

    static const ::std::string& ice_staticId();

private: 
    virtual ::std::shared_ptr<::Ice::ObjectPrx> __newInstance() const;
};

}

namespace Ice
{

template<>
struct InterfaceTraits<::Demo::Hello>
{
    static const std::string staticId;
    static const int compactId = -1;
};

}

namespace Demo
{

class Hello : virtual public ::Ice::Object
{
public:

    typedef HelloPrx ProxyType;

    virtual bool ice_isA(::std::string, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void sayHello(int, const ::Ice::Current& = ::Ice::Current()) = 0;

    ::Ice::DispatchStatus ___sayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void shutdown(const ::Ice::Current& = ::Ice::Current()) = 0;

    ::Ice::DispatchStatus ___shutdown(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);
};

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
