// Copyright (c) ZeroC, Inc.

package com.example.ice.greeter.server;

import com.example.visitorcenter.Greeter;
import com.zeroc.Ice.Current;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements Greeter
{
    // Implements the abstract method 'greet' from the Greeter interface generated by the Slice compiler.
    // This variant is the synchronous implementation.
    public String greet(String name, Current current) {
        System.out.println("Dispatching greet request { name = '" + name + "' }");
        return "Hello, " + name + "!";
    }
}
