// Copyright (c) ZeroC, Inc.

import Foundation
import Ice

// Create an Ice communicator to initialize the Ice runtime.
let communicator = try Ice.initialize()

// Destroy the communicator when the program exits.
defer {
    communicator.destroy()
}

// GreeterPrx is a class generated by the Slice compiler. We create a proxy from a communicator and a "stringified
// proxy" with the address of the target object.
// If you run the server on a different computer, replace localhost in the string below with the server's hostname
// or IP address.
let greeter = try makeProxy(
    communicator: communicator, proxyString: "greeter:tcp -h localhost -p 4061",
    type: GreeterPrx.self)

// Send a request to the remote object and get the response.
let greeting = try await greeter.greet(NSUserName())

print(greeting)
