% Copyright (c) ZeroC, Inc.

function client(args)
    arguments (Repeating)
        args (1, :) char
    end

    % Load the Ice library if it is not already loaded.
    if ~libisloaded('ice')
        loadlibrary('ice', @iceproto);
    end

    % Set the Ice.ImplicitContext property to 'Shared'. This is only necessary for the implicit context API (see below).
    properties = Ice.Properties(args);
    properties.setProperty('Ice.ImplicitContext', 'Shared');

    % Create an Ice communicator. We'll use this communicator to create proxies and manage outgoing connections.
    communicator = Ice.Communicator(Properties = properties);

    % Destroy the communicator when the function exits.
    cleanup = onCleanup(@() communicator.destroy());

    % GreeterPrx is a class generated by the Slice compiler. We create a proxy from a communicator and a
    % "stringified proxy" with the address of the target object.
    % If you run the server on a different computer, replace localhost in the string below with the server's hostname
    % or IP address.
    greeter = visitorcenter.GreeterPrx(communicator, 'greeter:tcp -h localhost -p 4061');

    % Create a request context.
    context = configureDictionary('string', 'string');

    % Send a request to the remote object and get the response. We request a French greeting by setting 'language' in
    % the context parameter.
    context('language') = 'fr';
    greeting = greeter.greet(char(java.lang.System.getProperty('user.name')), context);
    fprintf('%s\n', greeting);

    % Do it again, this time by setting the context on the proxy.
    context('language') = 'es';
    greeterEs = greeter.ice_context(context);
    greeting = greeterEs.greet('alice');
    fprintf('%s\n', greeting);

    % One more time, this time with an implicit context set on the communicator.
    communicator.getImplicitContext().put('language', 'de');
    greeting = greeter.greet('bob');
    fprintf('%s\n', greeting);
end
