// Copyright (c) ZeroC, Inc.

package com.example.icestorm.weather.station;

import com.example.clearsky.AtmosphericConditions;
import com.example.clearsky.WeatherStation;
import com.zeroc.Ice.Current;

/**
 * ConsolePrinter is an Ice servant that implements Slice interface WeatherStation.
 */
class ConsolePrinter implements WeatherStation {
    // Implements the abstract method 'report' from the WeatherStation interface generated by the Slice compiler.
    @Override
    public void report(String sensorId, String timeStamp, AtmosphericConditions conditions, Current current) {
        System.out.println(
            String.format("%s measured { Temperature = %.1f°C, Humidity = %.1f%% } at %s",
                sensorId, conditions.temperature, conditions.humidity, timeStamp)
        );
    }
}
