// Copyright (c) ZeroC, Inc.

#ifndef SIMPLE_WAKE_UP_SERVICE_H
#define SIMPLE_WAKE_UP_SERVICE_H

#include "AlarmClock.h"

#include <future>
#include <vector>

namespace Server
{
    /// SimpleWakeUpService is an Ice servant that implements Slice interface WakeUpService.
    class SimpleWakeUpService : public EarlyRiser::WakeUpService
    {
    public:
        // Waits for all outstanding tasks to complete.
        ~SimpleWakeUpService() override;

        // Implements the pure virtual function in the base class (WakeUpService) generated by the Slice compiler.
        void wakeMeUp(std::optional<EarlyRiser::AlarmClockPrx> alarmClock, std::int64_t timeStamp, const Ice::Current&)
            override;

    private:
        std::vector<std::future<void>> _tasks;
    };
}

#endif
