<?php
// Copyright (c) ZeroC, Inc.

require_once 'Ice.php';
require_once 'Greeter.php';

try {
    // Get the username from the POST request or use a default value
    $username = isset($_POST['username']) ? $_POST['username'] : 'PHP';

    // Try to find a registered "Greeter" communicator, or create and register a new one if not found.
    $communicator = Ice\find('Greeter');
    if ($communicator === null) {
        $communicator = Ice\initialize();
        Ice\register($communicator, 'Greeter');
    }

    // GreeterPrxHelper is a class generated by the Slice compiler. We create a Greeter proxy from a communicator and a
    // "stringified proxy" with the address of the target object. "host.docker.internal" is used to connect to the
    // Greeter server running on the host machine from within a Docker container.
    $greeter = VisitorCenter\GreeterPrxHelper::createProxy(
        $communicator,
        'greeter:tcp -h host.docker.internal -p 4061');

    // Send a request to the remote object and get the response.
    $greeting = $greeter->greet($username);

    // Display the greeting in an HTML page
    echo "<!DOCTYPE html><html><body>";
    echo "<h1>Greeting from Ice server:</h1>";
    echo "<p>" . htmlspecialchars($greeting) . "</p>";
    echo '<p><a href="index.html">Back</a></p>';
    echo "</body></html>";
} catch (Exception $e) {
    echo "<p>Error: " . htmlspecialchars($e->getMessage()) . "</p>";
}
