// Copyright (c) ZeroC, Inc.

#ifndef CHATBOT_AMD_H
#define CHATBOT_AMD_H

#include "Greeter.h"

#include <future>
#include <vector>

namespace ServerAMD
{
    /// Chatbot is an Ice servant that implements Slice interface Greeter.
    class Chatbot : public VisitorCenter::AsyncGreeter
    {
    public:
        // Waits for all outstanding tasks to complete.
        ~Chatbot() override;

        // Implements the pure virtual function in the base class (VisitorCenter::AsyncGreeter) generated by the Slice
        // compiler.
        void greetAsync(
            std::string name,
            std::function<void(std::string_view returnValue)> response,
            std::function<void(std::exception_ptr)> exception,
            const Ice::Current& current) override;

    private:
        std::vector<std::future<void>> _tasks;
    };
}

#endif
