// Copyright (c) ZeroC, Inc.

package com.example.ice.optional.server1;

import com.example.clearsky.AtmosphericConditions;
import com.example.clearsky.WeatherStation;
import com.zeroc.Ice.Current;

/**
 * ConsolePrinter is an Ice servant that implements Slice interface WeatherStation.
 */
class ConsolePrinter implements WeatherStation {
    // Implements the abstract method 'report' from the WeatherStation interface generated by the Slice compiler.
    @Override
    public void report(String sensorId, AtmosphericConditions conditions, Current current) {
        System.out.println(
            String.format("%s reported { Temperature = %.1f°C, Humidity = %.1f%% } to station v1",
                sensorId, conditions.temperature, conditions.humidity)
        );
    }
}
