# Copyright (c) ZeroC, Inc.

import Ice

from ClearSky import WeatherStation, AtmosphericConditions

class ConsolePrinter(WeatherStation):
    """
    ConsolePrinter is an Ice servant that implements Slice interface WeatherStation.
    """

    # Implements the method report from the WeatherStation class generated by the Slice compiler.
    def report(self, sensorId: str, timeStamp: str, reading: AtmosphericConditions, current: Ice.Current) -> None:
        print(f"{sensorId} measured {reading} at {timeStamp}")
