#
# Application-specific configuration
#

# The address of the target object. `default` is replaced by the value of Ice.Default.Protocol.
Greeter.Proxy=greeter:default -h localhost -p 4061

#
# Ice configuration
#

# The transport protocol to use for Ice communications when `default` is specified.
# You can set it to tcp, ssl, ws, or wss. Leaving it unset is equivalent to setting it to tcp.
# Make sure you use the same value in client.conf and server.conf.
Ice.Default.Protocol=ssl

#
# IceSSL configuration
#

# The directory where the application finds certificates and other files.
IceSSL.DefaultDir=../../../../certs

# The keystore containing this client's certificate.
IceSSL.Keystore=client.p12

# The keystore the client uses to identify trusted peers.
IceSSL.Truststore=ca.p12

# The password used to read the keystores and decrypt the private key.
IceSSL.Password=password
IceSSL.KeystorePassword=password
IceSSL.TruststorePassword=password

# Turn on security logging/tracing.
# IceSSL.Trace.Security=1
