// Copyright (c) ZeroC, Inc.

#ifndef CHATBOT_H
#define CHATBOT_H

#include "Greeter.h"

namespace Server
{
    /// Chatbot is an Ice servant that implements Slice interface Greeter.
    class Chatbot : public VisitorCenter::Greeter
    {
    public:
        /// Creates a new Chatbot instance.
        /// @param delay The delay before returning each greeting.
        /// @param cancelDispatch A shared future that triggers the cancellation of all dispatches.
        Chatbot(std::chrono::milliseconds delay, std::shared_future<void> cancelDispatch);

        // Implements the pure virtual function in the base class (VisitorCenter::Greeter) generated by the Slice
        // compiler.
        std::string greet(std::string name, const Ice::Current&) override;

    private:
        std::shared_future<void> _cancelDispatch;
        std::chrono::milliseconds _delay;
    };
}

#endif
