import { Ice } from "@zeroc/ice";
import { EarlyRiser } from "./AlarmClock.js";

export class MockAlarmClock extends EarlyRiser.AlarmClock {
    private _needMoreTime = true;
    private _resolver: (value: void | PromiseLike<void>) => void;

    public StopPressed = new Promise<void>((resolve, reject) => (this._resolver = resolve));

    // Implements the abstract method ring from the AlarmClock class generated by the Slice compiler.
    ring(message: string, current: Ice.Current): EarlyRiser.ButtonPressed | Promise<EarlyRiser.ButtonPressed> {
        console.log(`Dispatching ring request { message = '${message}' }`);
        if (this._needMoreTime) {
            console.log("Returning ButtonPressed.Snooze to request more time.");
            this._needMoreTime = false; // we only snooze one time
            return EarlyRiser.ButtonPressed.Snooze;
        } else {
            this._resolver();
            console.log("Returning ButtonPressed.Stop to stop the alarm.");
            return EarlyRiser.ButtonPressed.Stop;
        }
    }
}
