# **********************************************************************
#
# Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
#
# **********************************************************************

top_srcdir	= ../..

SLICE_SRCS	= Value.ice

include $(top_srcdir)/make/Make.rules
