// Copyright (c) ZeroC, Inc.

package com.example.ice.customerror.server;

import com.example.visitorcenter.Greeter;
import com.example.visitorcenter.GreeterError;
import com.example.visitorcenter.GreeterException;
import com.zeroc.Ice.Current;
import com.zeroc.Ice.DispatchException;
import com.zeroc.Ice.ObjectNotExistException;
import static com.zeroc.Ice.ReplyStatus.Unauthorized;
import java.time.LocalDateTime;

/**
 * Chatbot is an Ice servant that implements Slice interface Greeter.
 */
class Chatbot implements Greeter
{
    private final int MaxLength = 7;

    // Implements the abstract method 'greet' from the Greeter interface generated by the Slice compiler.
    public String greet(String name, Current current) throws GreeterException {
        System.out.println("Dispatching greet request { name = '" + name + "' }");

        // Depending on the name, we return a greeting or throw an exception.
        return switch (name)
        {
            case "" ->
                // ObjectNotExistException is a dispatch exception with a reply status of 'ObjectNotExist'.
                throw new ObjectNotExistException();
            case "alice" ->
                // / Simulate an authentication error by throwing a dispatch exception with the Unauthorized error code.
                // Note: This is a demo; no real authentication logic is implemented.
                throw new DispatchException(
                    Unauthorized.value(),
                    "Invalid credentials. The administrator has been notified.");
            case "bob" ->
                throw new GreeterException("Away until "
                    + LocalDateTime.now().plusMinutes(5L) + ".", GreeterError.Away);
            case "carol" ->
                throw new GreeterException("I am already greeting someone else.", GreeterError.GreetingOtherVisitor);
            default ->
            {
                if (name.length() > MaxLength) {
                    throw new GreeterException("Name is longer than maximum!", GreeterError.NameTooLong);
                } else {
                    yield "Hello, " + name + "!";
                }
            }
        };
    }
}
