// Copyright (c) ZeroC, Inc.

#ifndef CHATBOT_H
#define CHATBOT_H

#include "Greeter.h"

namespace Server
{
    /// Chatbot is an Ice servant that implements Slice interface Greeter.
    class Chatbot : public VisitorCenter::Greeter
    {
    public:
        /// Constructs a new Chatbot instance.
        /// @param chatbotName
        Chatbot(std::string chatbotName);

        // Implements the pure virtual function in the base class (VisitorCenter::Greeter) generated by the Slice
        // compiler.
        std::string greet(std::string name, const Ice::Current&) override;

    private:
        const std::string _chatbotName;
    };
}

#endif
