// Copyright (c) ZeroC, Inc.

import Foundation
import Ice

/// BidirWakeUpService is an Ice servant that implements Slice interface WakeUpService.
class BidirWakeUpService: WakeUpService {
    // Implements the protocol method wakeMeUp from the WakeUpService protocol generated by the Slice compiler.
    func wakeMeUp(timeStamp: Int64, current: Ice.Current) throws {
        let wakeUpTime = Date(timeStamp: timeStamp)

        print("Dispatching wakeMeUp request { wake up time = '\(wakeUpTime.formatted(date: .omitted, time: .complete))' }")

        guard let connection = current.con else {
            throw Ice.FeatureNotSupportedException("BidirWakeUpService does not support collocated calls")
        }

        // Create a proxy to the client's alarm clock. This connection-bound proxy is called a "fixed proxy".
        let alarmClock = try uncheckedCast(
            prx: connection.createProxy(Ice.Identity(name: "alarmClock")), type: AlarmClockPrx.self)

        // Schedule a wake-up call in a background task.
        Task {
            // Sleep until the wake up time.
            try await Task.sleep(for: .seconds(wakeUpTime.timeIntervalSince(Date())))

            // First ring. This invocation reuses the connection established by the client.
            var buttonPressed = try await alarmClock.ring("It's time to wake up!")

            // Keep ringing every 10 seconds until the user presses the stop button.
            while buttonPressed == .snooze {
                try await Task.sleep(for: .seconds(10)) // Sleep for 10 seconds.
                buttonPressed = try await alarmClock.ring("No more snoozing!")
            }
            print("Client pressed Stop on alarm clock.")
        }
    }
}
