// Copyright (c) ZeroC, Inc.

using VisitorCenter;

namespace Server;

/// <summary>Chatbot is an Ice servant that implements Slice interface Greeter.</summary>
internal class Chatbot : GreeterDisp_
{
    // Implements the abstract method Greet from the GreeterDisp_ class generated by the Slice compiler.
    public override string Greet(string name, Ice.Current current)
    {
        // We retrieve the value for the language entry in the context.
        if (!current.ctx.TryGetValue("language", out string? language))
        {
            language = "";
        }

        Console.WriteLine($"Dispatching greet request {{ name = '{name}', language = '{language}' }}");

        // Return a greeting in the requested language.
        return language switch
        {
            "de" => $"Hallo {name}, wie geht's?",
            "es" => $"¡Hola {name}!",
            "fr" => $"Bonjour {name}, comment vas-tu ?",
            _ => $"Hello, {name}!"
        };
    }
}
