// Copyright (c) ZeroC, Inc.

/// Makes AtmosphericConditions conform to the `CustomStringConvertible` protocol.
/// AtmosphericConditions is a class generated by the Slice compiler from a Slice class with the same name.
extension AtmosphericConditions: CustomStringConvertible {
    public var description: String {
        "{ Temperature = \(temperature)°C, Humidity = \(humidity)% }"
    }
}
