#!/usr/bin/env python
# Copyright (c) ZeroC, Inc.

import asyncio
import getpass
import sys

import Ice

# Slice module VisitorCenter in Greeter.ice maps to Python module VisitorCenter.
from VisitorCenter import GreeterPrx


async def main():
    # Create an Ice communicator. We'll use this communicator to create proxies, and manage outgoing connections. We
    # enable asyncio support by passing the current event loop to the communicator constructor.
    async with Ice.Communicator(sys.argv, eventLoop=asyncio.get_running_loop()) as communicator:
        # GreeterPrx is a class generated by the Slice compiler. We create a proxy from a communicator and a "stringified
        # proxy" with the address of the target object.
        # If you run the server on a different computer, replace localhost in the string below with the server's hostname
        # or IP address.
        greeter = GreeterPrx(communicator, "greeter:tcp -h localhost -p 4061")

        # Create a proxy to the slow greeter. It uses the same connection as the regular greeter.
        slowGreeter = GreeterPrx(communicator, "slowGreeter:tcp -h localhost -p 4061")

        # Send a request to the regular greeter and get the response.
        greeting = await greeter.greetAsync(getpass.getuser())
        print(greeting)

        # Create another slow greeter proxy with an invocation timeout of 4 seconds (the default invocation timeout is
        # infinite).
        slowGreeter4s = slowGreeter.ice_invocationTimeout(4000)  # in milliseconds

        # Send a request to the slow greeter with the 4-second invocation timeout.
        try:
            greeting = await slowGreeter4s.greetAsync("alice")
            print(f"Received unexpected greeting: {greeting}")
        except Ice.InvocationTimeoutException as exception:
            print(f"Caught InvocationTimeoutException, as expected: {exception}")

        # Verify the regular greeter still works.
        greeting = await greeter.greetAsync("bob")
        print(greeting)

        # Send a request to the slow greeter, and wait forever for the response.
        print("Please press Ctrl+C in the server's terminal to cancel the slow greeter dispatch.")
        try:
            greeting = await slowGreeter.greetAsync("carol")
            print(greeting)
        except Ice.UnknownException as exception:
            print(f"Caught UnknownException, as expected: {exception}")


if __name__ == "__main__":
    asyncio.run(main())
