#!/usr/bin/env python
# Copyright (c) ZeroC, Inc.

import Ice
import asyncio
import getpass
import sys

# Slice module VisitorCenter in Greeter.ice maps to Python module VisitorCenter.
from VisitorCenter import GreeterPrx

async def main():
    # Create an Ice communicator. We'll use this communicator to create proxies, and manage outgoing connections. We
    # enable asyncio support by passing the current event loop to initialize.
    with Ice.initialize(sys.argv, eventLoop=asyncio.get_running_loop()) as communicator:

        # GreeterPrx is a class generated by the Slice compiler. We create a proxy from a communicator and a "stringified
        # proxy" with the address of the target object.
        # If you run the server on a different computer, replace localhost in the string below with the server's hostname
        # or IP address.
        greeter = GreeterPrx(communicator, "greeter:tcp -h localhost -p 4061")

        # Create a proxy to the slow greeter with an invocation timeout of 4 seconds (the default invocation timeout is
        # infinite).
        slowGreeter = GreeterPrx(communicator, "slowGreeter:tcp -h localhost -p 4061").ice_invocationTimeout(4000)

        # Send a request to the regular greeter and get the response.
        greeting = await greeter.greetAsync(getpass.getuser())
        print(greeting)

        # Send a request to the slow greeter with the 4-second invocation timeout.
        try:
            greeting = await slowGreeter.greetAsync("alice")
            print(f"Received unexpected greeting: {greeting}")
        except Ice.InvocationTimeoutException as exception:
            print(f"Caught InvocationTimeoutException, as expected: {exception}")

        # Verify the regular greeter still works.
        greeting = await greeter.greetAsync("carol")
        print(greeting)

if __name__ == "__main__":
    asyncio.run(main())
