// Copyright (c) ZeroC, Inc.

// Slice module VisitorCenter in Greeter.ice maps to C# namespace VisitorCenter.
using VisitorCenter;

// Create an Ice communicator. We'll use this communicator to create proxies and manage outgoing connections.
await using Ice.Communicator communicator = Ice.Util.initialize(ref args);

// GreeterPrx is a class generated by the Slice compiler. We create a proxy from a communicator and a "stringified
// proxy" with the address of the target object.
// If you run the server on a different computer, replace localhost in the string below with the server's hostname
// or IP address.
GreeterPrx greeter = GreeterPrxHelper.createProxy(communicator, "greeter:tcp -h localhost -p 4061");

string[] names = ["", "jimmy", "billy bob", "alice", Environment.UserName];
string greeting;

foreach (string name in names)
{
    // Send a request to the remote object and get the response.
    try
    {
        greeting = await greeter.GreetAsync(name);
        Console.WriteLine(greeting);
    }
    catch (GreeterException grExcept)
    {
        Console.WriteLine($"Exception caught: {grExcept.error}\n {grExcept.reason}");
    }
}
