#!/usr/bin/env ruby
# Copyright (c) ZeroC, Inc.

require 'Ice'

# Load the code generated by the Slice compiler. The Slice module ClearSky maps to a Ruby module with the same name.
require_relative 'WeatherStation.rb'

# Create an Ice communicator. We'll use this communicator to create proxies and manage outgoing connections.
Ice.initialize(ARGV) do |communicator|
    # Create a proxy to the weather station.
    weatherStation = ClearSky::WeatherStationPrx.new(communicator, "weatherStation:tcp -h localhost -p 4061")

    # Generate random temperature and humidity values.
    temperature = (190.0 + rand(40)) / 10.0 # Temperature in degrees Celsius (19.0 to 23.0).
    humidity = (450.0 + rand(100)) / 10.0   # Humidity in percentage (45.0 to 55.0).

    # Create an AtmosphericConditions object with random values.
    reading = ClearSky::AtmosphericConditions.new(temperature, humidity)

    # Report this reading to the weather station.
    weatherStation.report("sensor v1", reading)

    puts "sensor v1: sent reading to weather station"
end
