# Copyright (c) ZeroC, Inc.

import Ice

# Slice module VisitorCenter in Greeter.ice maps to Python module VisitorCenter.
import VisitorCenter

class Chatbot(VisitorCenter.Greeter):
    """
    Chatbot is an Ice servant that implements Slice interface Greeter.
    """

    # Implements the method greet from the Greeter class generated by the Slice compiler.
    def greet(self, name: str, current: Ice.Current) -> str:
        # We retrieve the value for the language entry in the context.
        print(f"Context: {current.ctx}")
        language = current.ctx.get("language", "")

        print(f"Dispatching greet request {{ name = '{name}', language = '{language}' }}")

        # Return a greeting in the requested language.
        match language:
            case "de":
                return f"Hallo {name}, wie geht's?"
            case "es":
                return f"¡Hola {name}!"
            case "fr":
                return f"Bonjour {name}, comment vas-tu ?"
            case _:
                return f"Hello, {name}!"
