// Copyright (c) ZeroC, Inc.

using VisitorCenter;

namespace GreeterServer;

/// <summary>A Chatbot is an Ice servant that implements Slice interface Greeter.</summary>
internal class Chatbot : GreeterDisp_
{
    // Implements the abstract method greet from the GreeterDisp_ class generated by the Slice compiler.
    public override string greet(string name, Ice.Current current)
    {
        Console.WriteLine($"Dispatching greet request {{ name = '{name}' }}");
        return $"Hello, {name}!";
    }
}
