// Copyright (c) ZeroC, Inc.

namespace ClearSky;

/// <summary>Provides a custom ToString method for the AtmosphericConditions class generated by the Slice compiler.
/// </summary>
public partial class AtmosphericConditions
{
    /// <inheritdoc/>
    public override string ToString()
    {
        // If Pressure is null/not set, we display unknown with no unit.
        string pressureMb = Pressure is null ? "unknown" : $"{Pressure} mb";
        return $"{{ Temperature = {Temperature}°C, Humidity = {Humidity}%, Pressure = {pressureMb} }}";
    }
}
