name: Instal Nightly Ice

runs:
  using: "composite"
  steps:
    - name: Install Ice Brew Formula
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install zeroc-ice/nightly/ice

    - name: Install Ice Linux Repository
      if: runner.os == 'Linux'
      shell: bash
      run: |
        wget https://download.zeroc.com/ice/nightly/ubuntu24.04/ice-repo-nightly_1.0_all.deb -O ice-repo-nightly.deb
        sudo dpkg -i ice-repo-nightly.deb
        rm ice-repo-nightly.deb

        sudo apt-get update
        sudo apt-get install -y libzeroc-ice-dev
