name: Java

on:
  push:
    branches: ["3.8"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["3.8"]

permissions:
  contents: read

jobs:

  rewrite:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Run rewrite linter
        timeout-minutes: 20
        working-directory: java
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          Get-ChildItem -Recurse -Depth 2 -Filter gradlew | ForEach-Object {
            Push-Location $_.DirectoryName
            Write-Host "Building in $($_.DirectoryName)..."
            & ./gradlew rewriteDryRun --no-parallel --no-configuration-cache
            if ($LASTEXITCODE -ne 0) {
              throw "Build failed in $($_.DirectoryName)"
            }
            Pop-Location
          }
