name: Java

on:
  push:
    branches: ["3.8"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["3.8"]

jobs:

  rewrite:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Run rewrite linter
        timeout-minutes: 20
        working-directory: java
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          Get-ChildItem -Recurse -Depth 2 -Filter gradlew | ForEach-Object {
            Push-Location $_.DirectoryName
            Write-Host "Building in $($_.DirectoryName)..."
            & ./gradlew rewriteDryRun --no-parallel --no-configuration-cache
            if ($LASTEXITCODE -ne 0) {
              throw "Build failed in $($_.DirectoryName)"
            }
            Pop-Location
          }
