// Copyright (c) ZeroC, Inc.

namespace ClearSky;

/// <summary>Provides a custom ToString method for the AtmosphericConditions class generated by the Slice compiler.
/// </summary>
public partial class AtmosphericConditions
{
    /// <inheritdoc/>
    public override string ToString() => $"{{ Temperature = {Temperature}°C, Humidity = {Humidity}% }}";
}
