// Copyright (c) ZeroC, Inc.

using ClearSky;

namespace Station;

/// <summary>ConsolePrinter is an Ice servant that implements Slice interface WeatherStation. It prints all information
/// reported by the sensors to the console.</summary>
internal class ConsolePrinter : WeatherStationDisp_
{
    /// <inheritdoc/>
    // Implements the abstract method Report from the WeatherStationDisp_ class generated by the Slice compiler.
    public override void Report(string sensorId, string timeStamp, AtmosphericConditions? reading, Ice.Current current)
    {
        Console.WriteLine($"{sensorId} measured {reading} at {timeStamp}");
    }
}
