<?php
// Copyright (c) ZeroC, Inc.

require_once 'Ice.php';
require_once 'Greeter.php';

// Create an Ice communicator. We'll use this communicator to create proxies and manage outgoing connections.
$communicator = Ice\initialize($argv);

// GreeterPrxHelper is a class generated by the Slice compiler. We create a Greeter proxy from a communicator and a
// "stringified proxy" with the address of the target object.
// If you run the server on a different computer, replace localhost in the string below with the server's hostname
// or IP address.
$greeter = VisitorCenter\GreeterPrxHelper::createProxy($communicator, 'greeter:tcp -h localhost -p 4061');

// Send a request to the remote object and get the response. We request a French greeting by setting 'language' in
// the context parameter.
$context = ["language" => "fr"];
$greeting = $greeter->greet(get_current_user(), $context);
echo "$greeting\n";

// Do it again, this time by setting the context on the proxy.
$context = ["language" => "es"];
$greeterEs = $greeter->ice_context($context);
$greeting = $greeterEs->greet("alice");
echo "$greeting\n";

?>
